spring.application.name=TrailnCampPlanner
spring.datasource.url=jdbc:mysql://localhost:3306/trail_n_camp
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# This tells hibernate to automatically create a database tables if needed.
# It will also tell hibernate to update the tables if any changes are made to
# the JP entities.
spring.jpa.hibernate.ddl-auto=update

# Auth
jwt.secret=bXktc3VwZXItc2VjdXJlLXNlY3JldC1rZXktMTIzNDU2Nzg5MDEyMzQ1Ng==
# 1 hour = 3600000
jwt.expirationMilliseconds=3600000